theme = "tokyonight"

[editor]
line-number = "relative"
completion-timeout = 5
completion-replace = true
bufferline = "always"
color-modes = true
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
